### ISSUE TITLE
UI Text Color Issue

### ISSUE THREAD

**Issue by geekwolverine** [matfantinel/moneta#21]
The text in the UI is not visible. The background color overpowers the text color.
![Screenshot](https://user-images.githubusercontent.com/4777626/72995890-b03e4280-3e1f-11ea-9f78-080f05066163.png)

**Comment by matfantinel** [comment]
Are you on elementary with a custom theme or did you install from source?

Moneta was only tested with the elementary theme - it uses variables that are not available in most other themes. Technically the color issues can be solved by hardcoding the colors, but some elements might still look off with other themes.

I might take a look into hardcoding the colors next week, since I'm traveling right now.
